



















        self.stdout.write(self.style.SUCCESS('Database available'))                time.sleep(1)                self.stdout.write('Database unavailable, waiting for 1 sec...')            except (Psycopg2Error,OperationalError):                db_up = True                self.check(databases=['default']) # type: ignore            try:        while db_up is False:        db_up = False        self.stdout.write('Waiting for databases...')    def handle(self,*args,**options):class Command(BaseCommand):from django.db.utils import OperationalErrorfrom psycopg2 import OperationalError as Psycopg2Errorimport time from django.core.management.base import BaseCommand